#!/usr/bin/env bash
# =============================================================================
# G-10 / food-delivery: Noisy Logs Only Negative
# =============================================================================
# Root Cause: root 없음. 소량의 validation/noisy request만 생성해 text/log signal은
#             만들 수 있지만 measured root floor는 만들지 않는다.
#
# Usage:
#   ./scenario-07-noisy-logs-only.sh
#   ./scenario-07-noisy-logs-only.sh cleanup
# =============================================================================

set -uo pipefail

export KUBECONFIG=/home/nkia/.kube/food-delivery.yaml
NAMESPACE="rca-testbed-food"
ORDER_POD_LABEL="app=testbed-order"
RESULT_LOG="/tmp/g10-food-noisy-logs-results.log"
REQUESTS=30

RED='\033[0;31m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'; NC='\033[0m'
log_info()  { echo -e "${CYAN}[INFO]${NC} $(date '+%Y-%m-%d %H:%M:%S') $*"; }
log_ok()    { echo -e "${GREEN}[OK]${NC}   $(date '+%Y-%m-%d %H:%M:%S') $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $(date '+%Y-%m-%d %H:%M:%S') $*"; }

order_pod() {
    kubectl -n "$NAMESPACE" get pod -l "$ORDER_POD_LABEL" -o jsonpath='{.items[0].metadata.name}' 2>/dev/null
}

check_prerequisites() {
    local pod
    pod=$(order_pod)
    if [[ -z "$pod" ]]; then
        log_error "order-service pod not found"
        exit 1
    fi
}

send_invalid_requests() {
    local pod
    pod=$(order_pod)
    log_info "INJECTION_START_MS=$(date +%s%3N)"
    log_info "Sending small invalid-order sample: $REQUESTS requests"
    for i in $(seq 1 "$REQUESTS"); do
        kubectl -n "$NAMESPACE" exec "$pod" -- \
            curl -s -o /dev/null \
            -w "g10-invalid-${i}: HTTP %{http_code} in %{time_total}s\n" \
            --max-time 10 \
            -X POST "http://localhost:8080/api/orders" \
            -H "Content-Type: application/json" \
            -d "{\"customerId\":\"g10-noisy-${i}\",\"restaurantId\":999999,\"items\":[{\"menuId\":999999,\"qty\":1}]}" \
            >> "$RESULT_LOG" 2>&1 || true
        sleep 1
    done
}

analyze_results() {
    if [[ -f "$RESULT_LOG" ]]; then
        tail -n 20 "$RESULT_LOG"
    fi
}

cleanup() {
    rm -f "$RESULT_LOG"
    log_info "INJECTION_END_MS=$(date +%s%3N)"
    log_ok "Cleanup complete"
}

main() {
    if [[ "${1:-}" == "cleanup" ]]; then
        cleanup
        trap - EXIT
        exit 0
    fi
    echo "============================================================"
    echo "  G-10 food-delivery: Noisy Logs Only Negative"
    echo "  Start: $(date '+%Y-%m-%d %H:%M:%S')"
    echo "============================================================"
    trap cleanup EXIT
    check_prerequisites
    send_invalid_requests
    analyze_results
    log_info "No sustained load is generated by design."
    sleep 30
}

main "$@"
