#!/usr/bin/env bash
# =============================================================================
# G-6 / social-feed: KCM Lifecycle Without Service Impact Negative
# =============================================================================
# Root Cause: non-critical mock-push-gateway rollout/lifecycle event만 발생시키고
#             user-facing traffic은 만들지 않는다.
#
# Expected RCA: KCM event alone is not sufficient for conclusive root.
#
# Usage:
#   ./scenario-06-kcm-lifecycle-no-impact.sh
#   ./scenario-06-kcm-lifecycle-no-impact.sh cleanup
# =============================================================================

set -uo pipefail

# k3d 도메인별 클러스터: social 전용 kubeconfig (공유 config 의 current-context 드리프트 무관)
export KUBECONFIG="${KUBECONFIG:-/root/tb-kubeconfig}"
NAMESPACE="rca-testbed-social"
TARGET_DEPLOY="testbed-mock-push-gateway"
APP_POD_LABEL="app=testbed-post"
ORIG_REPLICAS_FILE="/tmp/g6-social-push-orig-replicas"
# k3d 는 호스트로 NodePort 를 publish 하지 않으므로, API 호출은 클러스터 내부에서
# 앱 파드(curl 보유) 를 kubectl exec 경유로 nginx 게이트웨이로 보낸다.
API_BASE="http://testbed-nginx-external"
RESULT_LOG="/tmp/g6-social-push-negative-results.log"
NOTIF_BURST=15
NOTIF_ROUNDS=4

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
log_info()  { echo -e "${CYAN}[INFO]${NC} $(date '+%Y-%m-%d %H:%M:%S') $*"; }
log_ok()    { echo -e "${GREEN}[OK]${NC}   $(date '+%Y-%m-%d %H:%M:%S') $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $(date '+%Y-%m-%d %H:%M:%S') $*"; }

# --- 클러스터 내부 HTTP 호출 헬퍼 (k3d: 호스트 NodePort 미노출 → 앱 파드 exec 경유) ---
API_POD=""
resolve_api_pod() {
    API_POD=$(kubectl -n "$NAMESPACE" get pod -l "$APP_POD_LABEL" \
        -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)
}
# api_curl: curl 과 동일 인자. URL 은 $API_BASE(=cluster nginx) 기준. 클러스터 안에서 실행됨.
api_curl() { kubectl -n "$NAMESPACE" exec "$API_POD" -- curl "$@"; }

check_prerequisites() {
    if ! kubectl -n "$NAMESPACE" get deploy "$TARGET_DEPLOY" &>/dev/null; then
        log_error "deployment not found: $TARGET_DEPLOY"
        exit 1
    fi
    resolve_api_pod
    if [[ -z "$API_POD" ]]; then
        log_error "post-service Pod 없음 (API 호출 불가)"
        exit 1
    fi
    kubectl -n "$NAMESPACE" get deploy "$TARGET_DEPLOY" -o jsonpath='{.spec.replicas}' > "$ORIG_REPLICAS_FILE"
}

induce_lifecycle_noise() {
    log_info "INJECTION_START_MS=$(date +%s%3N)"
    log_info "Scaling non-user-facing $TARGET_DEPLOY to zero without generating user traffic"
    kubectl -n "$NAMESPACE" scale deploy "$TARGET_DEPLOY" --replicas=0
    sleep 10
    kubectl -n "$NAMESPACE" get pods -l app="$TARGET_DEPLOY" -o wide 2>/dev/null || true
    log_ok "Lifecycle noise generated"
}

burst_notifications() {
    local round=$1
    local pids=()
    log_info "Round $round: notification requests while push gateway is unavailable"
    for i in $(seq 1 "$NOTIF_BURST"); do
        api_curl -s -o /dev/null \
            -w "g6-notification-${round}-${i}: HTTP %{http_code} in %{time_total}s\n" \
            --max-time 15 \
            -X POST "$API_BASE/api/notifications" \
            -H 'Content-Type: application/json' \
            -d "{\"userId\":1,\"message\":\"g6-push-negative-${round}-${i}\"}" \
            >> "$RESULT_LOG" 2>&1 &
        pids+=($!)
    done
    for pid in "${pids[@]}"; do wait "$pid" 2>/dev/null || true; done
}

cleanup() {
    local orig=1
    if [[ -f "$ORIG_REPLICAS_FILE" ]]; then
        orig=$(cat "$ORIG_REPLICAS_FILE")
    fi
    kubectl -n "$NAMESPACE" scale deploy "$TARGET_DEPLOY" --replicas="$orig" 2>/dev/null || true
    kubectl -n "$NAMESPACE" rollout status deploy "$TARGET_DEPLOY" --timeout=120s 2>/dev/null || true
    rm -f "$ORIG_REPLICAS_FILE" "$RESULT_LOG"
    log_info "INJECTION_END_MS=$(date +%s%3N)"
    log_ok "Cleanup complete (replicas=$orig)"
}

main() {
    if [[ "${1:-}" == "cleanup" ]]; then
        cleanup
        trap - EXIT
        exit 0
    fi
    echo "============================================================"
    echo "  G-6 social-feed: KCM Lifecycle Without Service Impact"
    echo "  Start: $(date '+%Y-%m-%d %H:%M:%S')"
    echo "============================================================"
    trap cleanup EXIT
    check_prerequisites
    induce_lifecycle_noise
    log_info "No feed/post user-facing request burst is generated by design."
    for round in $(seq 1 "$NOTIF_ROUNDS"); do
        burst_notifications "$round"
        sleep 8
    done
    [[ -f "$RESULT_LOG" ]] && tail -n 30 "$RESULT_LOG"
}

main "$@"
